# Generated by Django 4.2.7 on 2023-11-27 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_firsName', models.CharField(max_length=250)),
                ('user_lastName', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phoneNumber', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian phone number.', regex='^\\+98\\s?(\\d{2})\\s?(\\d{4})-(\\d{4})$')])),
            ],
        ),
    ]
