# Generated by Django 4.2.7 on 2023-11-28 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian phone number.', regex='^[\\+98 | 09 ]\\s?(\\d{2})\\s?(\\d{4})(\\d{4})$')]),
        ),
    ]
